version: '3.9'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    env_file: .env
    expose:
      - 8000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data_prod:
