# Generated by Django 4.2.13 on 2026-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPUNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=50, unique=True)),
                ("hostname", models.CharField(max_length=100)),
                ("gpu_model", models.CharField(max_length=100)),
                ("total_memory_gb", models.FloatField()),
                ("rack_id", models.CharField(max_length=50)),
                ("datacenter", models.CharField(default="DC-01", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("offline", "Offline"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GPU Node",
                "verbose_name_plural": "GPU Nodes",
                "ordering": ["node_id"],
            },
        ),
    ]
