# Generated by Django 4.2.13 on 2026-07-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IsolationForestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_blob", models.BinaryField()),
                ("feature_names", models.JSONField()),
                ("training_samples", models.IntegerField()),
                ("contamination", models.FloatField(default=0.05)),
                ("trained_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trained", "Trained"),
                            ("stale", "Stale"),
                            ("failed", "Failed"),
                        ],
                        default="trained",
                        max_length=20,
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isolation_forest_model",
                        to="cluster.gpunode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Isolation Forest Model",
                "verbose_name_plural": "Isolation Forest Models",
            },
        ),
        migrations.CreateModel(
            name="DriftScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("z_utilization", models.FloatField()),
                ("z_temperature", models.FloatField()),
                ("z_power", models.FloatField()),
                ("z_memory", models.FloatField()),
                ("z_ecc", models.FloatField()),
                ("zscore_composite", models.FloatField()),
                ("if_anomaly_score", models.FloatField(blank=True, null=True)),
                ("if_is_anomaly", models.BooleanField(blank=True, null=True)),
                ("composite_score", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_scores",
                        to="cluster.gpunode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drift Score",
                "verbose_name_plural": "Drift Scores",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["node", "computed_at"],
                        name="detection_d_node_id_2f9863_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BaselineStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=50)),
                ("rolling_mean", models.FloatField()),
                ("rolling_std", models.FloatField()),
                ("sample_count", models.IntegerField()),
                ("window_hours", models.IntegerField(default=12)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="cluster.gpunode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline Stats",
                "verbose_name_plural": "Baseline Stats",
                "unique_together": {("node", "metric_name")},
            },
        ),
    ]
