# Generated by Django 4.2.13 on 2026-07-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetrySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("utilization_pct", models.FloatField()),
                ("memory_used_gb", models.FloatField()),
                ("temperature_c", models.FloatField()),
                ("power_draw_w", models.FloatField()),
                ("ecc_errors", models.IntegerField(default=0)),
                ("fan_speed_pct", models.FloatField(default=0.0)),
                ("sm_clock_mhz", models.FloatField(default=0.0)),
                ("is_injected_failure", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_snapshots",
                        to="cluster.gpunode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telemetry Snapshot",
                "verbose_name_plural": "Telemetry Snapshots",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["node", "timestamp"],
                        name="telemetry_t_node_id_9d3de5_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="telemetry_t_timesta_ff7b54_idx"
                    ),
                ],
            },
        ),
    ]
